version: '3'

services:

  nginx:
    image: jwilder/nginx-proxy
    restart: always
    environment:
      - TRUST_DOWNSTREAM_PROXY=false
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost:/etc/nginx/vhost.d:rw
      - ./certs:/etc/nginx/certs:rw
      - ./html:/usr/share/nginx/html:rw
      - ./acme.sh:/etc/acme.sh:rw
    ports:
      - "80:80"
      - "443:443"

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=REPLACE_EMAIL@example.com

  myapp:
    restart: always
    image: myapp
    build: 
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: replace.this.host
      LETSENCRYPT_HOST: replace.this.host
      VIRTUAL_PORT: 8080
      SECRET_KEY: sdpf9sdp0vm_REPLACE_WITH_COMPLETERANDOM_0sdu34i23u890fum8
      MATPLOTLIB: false
    volumes:
      - ./app:/opt/myapp
      - ./niceguistorage:/opt/.nicegui:rw
    command: ["python3", "-u", "/opt/myapp/main.py"]

volumes:
  niceguistorage:
